---
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /mnt/docker/jellyfin/library:/config
      - /mnt/media/downloads:/data/movies
    ports:
      - 8096:8096
    restart: unless-stopped
