---
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    environment:
      TZ: Europe/Amsterdam
    volumes:
      - /mnt/docker/jellyfin/config:/config:rw
      - /mnt/media:/media:rw
    restart: unless-stopped
    network_mode: host